= Quarkus WireMock

include::./includes/attributes.adoc[]

Quarkus https://wiremock.org[WireMock] extension for tests and local development.
This extension starts `WireMock` as a `Dev Service`, thus it is designed to run in `dev` and `test` mode only!

== Installation

If you want to use this extension, you need to add the `io.quarkiverse.wiremock:quarkus-wiremock` dependency to your build file first.

For instance, with Maven, add the following dependency to your POM file:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.quarkiverse.wiremock</groupId>
    <artifactId>quarkus-wiremock</artifactId>
    <version>{project-version}</version>
    <scope>provided</scope>
</dependency>
----

== Usage

The extension comes with most reasonable defaults.
[source,properties]
----
quarkus.wiremock.devservices.enabled=true
quarkus.wiremock.devservices.reload=true
quarkus.wiremock.devservices.files-mapping=src/test/resources
quarkus.wiremock.devservices.global-response-templating=false
----

IMPORTANT: Due to its build time nature is totally fine that Quarkus prints `unrecognized configuration key` warnings when executing integration tests.

TIP: Starting the WireMock `Dev Service` doesn't automatically redirect your `@RestClient` calls to it; see xref:redirecting-rest-clients-to-wiremock[Redirecting REST Clients to WireMock] below.

== Testing

=== Stubbing & Verifying

A core feature of WireMock is the ability to return HTTP responses for request matching criteria. You can configure stubs using JSON configuration files placed in the `mappings` and `__files` folders.
The root location of these folders can be defined via `quarkus.wiremock.devservices.files-mapping`. By default the root location points to `src/test/resources`.

In addition, you might want to configure `WireMock's` stubbing and request matching behavior programmatically. To do so, please add the following dependency to your target project:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.quarkiverse.wiremock</groupId>
    <artifactId>quarkus-wiremock-test</artifactId>
    <version>{project-version}</version>
    <scope>test</scope>
</dependency>
----

After that, a `WireMock` client reference can be injected along with your test execution lifecycle as shown below:
[source,java]
----
@QuarkusTest
@ConnectWireMock
class WireMockDevServiceResourceTest {

    private static final String MOCK_MSG = "Hello from WireMock!";

    WireMock wiremock; // will be injected automatically when the test class is annotated with @ConnectWireMock

    @Test
    void testHelloEndpoint() {
        Assertions.assertNotNull(wiremock);
        wiremock.register(get(urlEqualTo("/mock-me"))
            .willReturn(aResponse().withStatus(200).withBody(MOCK_MSG)));
        ...
    }

}
----

TIP: For more details please refer to the WireMock https://wiremock.org/docs/stubbing/[Stubbing & Verifying] docs.

=== Redirecting REST Clients to WireMock

By default, starting the `WireMock` server does *not* rewire your application's outgoing calls to go through it.
If you're using a MicroProfile/Quarkus `@RestClient`, you still need to point its base URL at the WireMock `Dev Service` for your requests to actually reach it and match your stubs.

The easiest way is to set the `restClient` attribute of `@ConnectWireMock`:

[source,java]
----
@QuarkusTest
@ConnectWireMock(restClient = "my-api") // <1>
class WireMockDevServiceResourceTest {

    private static final String MOCK_MSG = "Hello from WireMock!";

    WireMock wiremock;

    @RestClient
    MyApiClient myApiClient; // <2>

    @Test
    void testHelloEndpoint() {
        wiremock.register(get(urlEqualTo("/mock-me"))
            .willReturn(aResponse().withStatus(200).withBody(MOCK_MSG)));

        assertEquals(MOCK_MSG, myApiClient.hello()); // <3>
    }

}
----
<1> `my-api` must match the configured name of your REST client (i.e. as used in `quarkus.rest-client.my-api.url`, or the client's `@RegisterRestClient(configKey = "my-api")`).
<2> No manual configuration needed: the client's base URL is redirected to WireMock automatically for the duration of the test.
<3> Requests now reach WireMock instead of the real downstream API, so your registered stubs get matched.

`restClient` is left empty by default, since an application can have multiple REST clients and only some of them may need to be redirected to WireMock in a given test.
`@ConnectWireMock` is repeatable, so redirect more than one REST client by repeating it:

[source,java]
----
@QuarkusTest
@ConnectWireMock(restClient = "my-api")
@ConnectWireMock(restClient = "my-other-api")
class WireMockDevServiceResourceTest {
    ...
}
----

If you'd rather configure this yourself (e.g. you need more control, or you're not using `@ConnectWireMock`), you can set the client's URL manually, typically in a test-only properties file (e.g. `src/test/resources/application.properties`):

[source,properties]
----
quarkus.rest-client.my-api.url=http://localhost:${quarkus.wiremock.devservices.port}
----

=== Configuration retrieval

This Quarkus extension exposes configuration keys via Java constants (`WireMockConfigKey`). By doing so, the config values can be accessed more easily:
[source,java]
----
@QuarkusTest
class WireMockDevServiceResourceTest {

    // WireMockConfigKey is provided by the core module and does not require the `test` module dependency
    @ConfigProperty(name = WireMockConfigKey.PORT)
    Integer port; // the port WireMock server is listening on

}
----

You can even access the WireMock `Dev Service` configuration values from within a Quarkus Integration Test:

[source,java]
----
@QuarkusIntegrationTest
@ConnectWireMock
class WireMockDevServiceResourceTest {

    DevServicesContext devServicesContext;

    @Test
    void testWireMockDevServiceConfigPropagation() {
        // Dev Service config gets propagated and is accessible via the ConfigProvider API
        int port = ConfigProvider.getConfig().getValue(WireMockConfigKey.PORT, Integer.class);

        // or via the Dev Service Context
        int portDevSerCtx = Integer.parseInt(devServicesContext.devServicesProperties().get(WireMockConfigKey.PORT));
        ...
    }

}
----

IMPORTANT: Please be aware that Dependency Injection (DI) works for specific types (`DevServicesContext` and `WireMock`) only.
The latter in particular is only available if the class has been annotated with `@ConnectWireMock`.

You can also reuse a `@QuarkusTest` as a `@QuarkusIntegrationTest` where applicable:
[source,java]
----
@QuarkusIntegrationTest
public class WireMockDevServiceResourceIT extends WireMockDevServiceResourceTest {
    // re-use Quarkus tests as integration tests
}
----

Further more this extension supports the configuration capabilities of Quarkus. This means you can reference `WireMock` configuration keys
within your custom properties via variable interpolation.
[source,properties]
----
custom.config.wiremock.url=http://localhost:${quarkus.wiremock.devservices.port}/mock-me
----

TIP: Please refer to https://quarkus.io/guides/config-reference#property-expressions[Property Expressions] for further details.

== Logging

The verbosity of the WireMock log output can be controlled through:
[source,properties]
----
quarkus.log.category."io.quarkiverse.wiremock.devservice.WireMockServer".level=ERROR
----


[[extension-configuration-reference]]
== Extension Configuration Reference

include::includes/quarkus-wiremock-devservices.adoc[leveloffset=+1, opts=optional]
